name: CI
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run Tests
        run: yarn test
      - name: Run VSCode Tests
        run: yarn run test-vscode

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Linter
        run: yarn run lint
      - name: Formatting
        run: yarn run format-check
